credentials:
  usernames:
    user1:
      email: user1@example.com
      name: User One
      password: hashedpassword1
    user2:
      email: user2@example.com
      name: User Two
      password: hashedpassword2

cookie:
  expiry_days: 30
  key: my_secret_key
  name: my_cookie_name

preauthorized:
  emails:
    - preauth@example.com
